# Generated by Django 3.1.6 on 2021-02-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC_CODE', models.CharField(max_length=255)),
                ('SC_NAME', models.CharField(max_length=255)),
                ('OPEN', models.CharField(max_length=255)),
                ('HIGH', models.CharField(max_length=255)),
                ('LOW', models.CharField(max_length=255)),
                ('CLOSE', models.CharField(max_length=255)),
            ],
        ),
    ]
